# Generated by Django 5.1.2 on 2024-12-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='우편번호'),
        ),
        migrations.AddField(
            model_name='member',
            name='address_default',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='기본주소'),
        ),
        migrations.AddField(
            model_name='member',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='상세주소'),
        ),
    ]
