# Generated by Django 5.1.2 on 2024-11-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_category_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="display",
            name="display_code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
