# Generated by Django 5.1.2 on 2024-11-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_display_display_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="display",
            name="display_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
