# Generated by Django 5.1.2 on 2024-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_product_product_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "상품 카테고리",
                "verbose_name_plural": "상품 카테고리",
            },
        ),
        migrations.AlterModelOptions(
            name="display",
            options={
                "verbose_name": "상품 진열방식",
                "verbose_name_plural": "상품 진열방식",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "상품", "verbose_name_plural": "상품"},
        ),
        migrations.AlterField(
            model_name="product",
            name="product_optional_products",
            field=models.ManyToManyField(
                blank=True, related_name="optional_product", to="dashboard.product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_related_products",
            field=models.ManyToManyField(
                blank=True, related_name="related_product", to="dashboard.product"
            ),
        ),
    ]
