# Generated by Django 5.1.2 on 2024-11-14 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_category_options_alter_display_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="상품 게시자",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_consumer_price",
            field=models.PositiveIntegerField(verbose_name="상품 소비자가"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100, verbose_name="상품명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_sell_price",
            field=models.PositiveIntegerField(verbose_name="상품 판매가"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_supply_price",
            field=models.PositiveIntegerField(verbose_name="상품 공급가"),
        ),
    ]
