# Generated by Django 5.1.2 on 2024-11-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_product_product_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="카테고리 설명"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=50, verbose_name="카테고리명"),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.category",
                verbose_name="부모 카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_seo_author",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="검색용 게시자"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_seo_description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="검색용 요약설명"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_seo_keywords",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="검색용 검색어"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_seo_title",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="검색용 사이트 제목"
            ),
        ),
        migrations.AlterField(
            model_name="display",
            name="display_code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="진열방식 코드"
            ),
        ),
        migrations.AlterField(
            model_name="display",
            name="display_description",
            field=models.CharField(max_length=100, verbose_name="진열방식 설명"),
        ),
        migrations.AlterField(
            model_name="display",
            name="display_name",
            field=models.CharField(max_length=50, verbose_name="진열방식명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_alternative_price",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="상품 판매가 대체 텍스트"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.ManyToManyField(
                related_name="product_category",
                to="dashboard.category",
                verbose_name="상품 카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.CharField(max_length=7, verbose_name="상품 분류코드"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(max_length=200, verbose_name="상품 요약설명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_detail",
            field=models.CharField(max_length=2000, verbose_name="상품 상세페이지"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_display",
            field=models.ManyToManyField(
                related_name="product_display",
                to="dashboard.display",
                verbose_name="상품 진열방식",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_keywords",
            field=models.CharField(max_length=500, verbose_name="상품 검색어"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_manage_name",
            field=models.CharField(max_length=100, verbose_name="상품명 (관리용)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_optional_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="optional_product",
                to="dashboard.product",
                verbose_name="추가 상품 (같은 계열 상품)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_product",
                to="dashboard.product",
                verbose_name="관련 상품 (추천 상품)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_seo_author",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="검색용 게시자"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_seo_description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="검색용 요약설명"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_seo_keywords",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="검색용 검색어"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_seo_title",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="검색용 사이트 제목"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_thumbnail_image",
            field=models.BinaryField(verbose_name="상품 이미지"),
        ),
    ]
