# Generated by Django 5.1.2 on 2024-11-14 11:50

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_category_category_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="lft",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="rght",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="tree_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.category",
                verbose_name="부모 카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_optional_products",
            field=models.ManyToManyField(
                blank=True,
                to="dashboard.product",
                verbose_name="추가 상품 (같은 계열 상품)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_related_products",
            field=models.ManyToManyField(
                blank=True, to="dashboard.product", verbose_name="관련 상품 (추천 상품)"
            ),
        ),
    ]
