# Generated by Django 5.1.2 on 2024-11-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_category_level_category_lft_category_rght_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_parent",
            new_name="parent",
        ),
    ]
