# Generated by Django 5.1.2 on 2024-11-14 11:53

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_rename_category_parent_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="dashboard.category",
                verbose_name="부모 카테고리",
            ),
        ),
    ]
