# Generated by Django 5.1.2 on 2024-11-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_category_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="level",
        ),
        migrations.RemoveField(
            model_name="category",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="category",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="category",
            name="tree_id",
        ),
        migrations.AddField(
            model_name="category",
            name="category_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.category",
                verbose_name="부모 카테고리",
            ),
        ),
    ]
