# Generated by Django 5.1.2 on 2024-11-16 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_remove_category_level_remove_category_lft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_stock",
                    models.IntegerField(
                        default=0, max_length=5, verbose_name="상품 재고수량"
                    ),
                ),
                (
                    "product_option_name",
                    models.CharField(max_length=50, verbose_name="상품 옵션명"),
                ),
                (
                    "product_option_display_name",
                    models.CharField(max_length=100, verbose_name="상품 옵션명"),
                ),
                (
                    "product_option_price",
                    models.IntegerField(max_length=10, verbose_name="상품 옵션가"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 옵션",
                "verbose_name_plural": "상품 옵션",
            },
        ),
    ]
