# Generated by Django 5.1.2 on 2024-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_productoptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoptions",
            name="product_option_price",
            field=models.IntegerField(verbose_name="상품 옵션가"),
        ),
        migrations.AlterField(
            model_name="productoptions",
            name="product_stock",
            field=models.IntegerField(default=0, verbose_name="상품 재고수량"),
        ),
    ]
