# Generated by Django 5.1.2 on 2024-11-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_productoptions_product_option_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoptions",
            name="product_option_display_name",
            field=models.CharField(max_length=100, verbose_name="상품 옵션명 (관리용)"),
        ),
    ]
