# Generated by Django 5.1.2 on 2024-11-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_productoptions_product_option_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_code",
            field=models.CharField(
                default="0", max_length=50, verbose_name="카테고리 코드"
            ),
        ),
        migrations.AlterField(
            model_name="productoptions",
            name="product_option_price",
            field=models.IntegerField(default=0, verbose_name="상품 옵션가"),
        ),
    ]
