# Generated by Django 5.1.2 on 2024-11-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_category_category_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_display_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="카테고리명 (관리용)"
            ),
        ),
    ]
