# Generated by Django 5.1.2 on 2024-11-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_category_category_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_display_name",
        ),
    ]
