# Generated by Django 5.1.2 on 2024-11-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_remove_category_category_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_cafe24_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="카페24 상품코드"
            ),
        ),
    ]
