# Generated by Django 5.1.2 on 2024-11-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_product_product_cafe24_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoptions",
            name="product_option_title",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="상품 옵션제목"
            ),
        ),
    ]
