# Generated by Django 5.1.2 on 2024-11-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_productoptions_product_option_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_author",
        ),
    ]
