# Generated by Django 5.1.2 on 2024-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_remove_product_product_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_display",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_display",
                to="dashboard.display",
                verbose_name="상품 진열방식",
            ),
        ),
    ]
