# Generated by Django 5.1.2 on 2024-11-23 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_alter_product_product_display"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="상품 게시자",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_created_datetime",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="상품 게시일자"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_modified_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="상품 수정일자"
            ),
        ),
    ]
