# Generated by Django 5.1.2 on 2024-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_product_product_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.CharField(
                max_length=7, unique=True, verbose_name="상품 분류코드"
            ),
        ),
    ]
