# Generated by Django 5.1.2 on 2024-11-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_alter_product_product_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_display",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_created_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="상품 게시일자"
            ),
        ),
        migrations.DeleteModel(
            name="Display",
        ),
    ]
