# Generated by Django 5.1.2 on 2024-11-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_remove_product_product_display_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productoptions",
            old_name="product_stock",
            new_name="product_option_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_optional_products",
        ),
        migrations.AddField(
            model_name="productoptions",
            name="product_option_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="상품 옵션코드"
            ),
        ),
    ]
