# Generated by Django 5.1.2 on 2024-12-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0026_rename_product_stock_productoptions_product_option_stock_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumer_id",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="고객 아이디"
                    ),
                ),
                (
                    "consumer_grade",
                    models.CharField(
                        choices=[
                            ("노바", "노바"),
                            ("오닉스", "오닉스"),
                            ("실버", "실버"),
                            ("골드", "골드"),
                            ("플래티넘", "플래티넘"),
                            ("티타늄", "티타늄"),
                            ("블랙 다이아몬드", "블랙 다이아몬드"),
                        ],
                        default="노바",
                        max_length=30,
                        verbose_name="고객 등급",
                    ),
                ),
                (
                    "consumer_name",
                    models.CharField(max_length=50, verbose_name="고객 이름"),
                ),
                (
                    "consumer_phone_number",
                    models.CharField(max_length=20, verbose_name="고객 전화번호"),
                ),
                (
                    "consumer_email",
                    models.CharField(max_length=50, verbose_name="고객 이메일"),
                ),
                (
                    "consumer_verified",
                    models.CharField(
                        choices=[("T", "인증됨"), ("F", "인증안됨")],
                        default="F",
                        max_length=10,
                        verbose_name="고객 인증여부",
                    ),
                ),
                ("consumer_birth", models.DateField(verbose_name="고객 생년월일")),
                (
                    "consumer_area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("경기", "경기"),
                            ("서울", "서울"),
                            ("인천", "인천"),
                            ("강원", "강원"),
                            ("충남", "충남"),
                            ("충북", "충북"),
                            ("대전", "대전"),
                            ("경북", "경북"),
                            ("경남", "경남"),
                            ("대구", "대구"),
                            ("부산", "부산"),
                            ("울산", "울산"),
                            ("전북", "전북"),
                            ("전남", "전남"),
                            ("광주", "광주"),
                            ("세종", "세종"),
                            ("제주", "제주"),
                            ("해외", "해외"),
                        ],
                        max_length=10,
                        verbose_name="고객 거주지역",
                    ),
                ),
                (
                    "consumer_base_address",
                    models.CharField(max_length=200, verbose_name="고객 기본주소"),
                ),
                (
                    "consumer_detail_address",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="고객 상세주소"
                    ),
                ),
                (
                    "consumer_refund_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="고객 환불계좌정보"
                    ),
                ),
                (
                    "consumer_total_visits",
                    models.IntegerField(default=0, verbose_name="고객 총 방문횟수"),
                ),
                (
                    "consumer_total_orders",
                    models.IntegerField(default=0, verbose_name="고객 총 실주문건수"),
                ),
                (
                    "consumer_total_purchase",
                    models.IntegerField(default=0, verbose_name="고객 총 구매금액"),
                ),
                (
                    "consumer_last_order_dt",
                    models.DateTimeField(blank=True, verbose_name="고객 최종주문일"),
                ),
                (
                    "consumer_last_connection_dt",
                    models.DateTimeField(blank=True, verbose_name="고객 최종접속일"),
                ),
                (
                    "consumer_register_dt",
                    models.DateField(verbose_name="고객 회원가입일"),
                ),
                (
                    "consumer_register_path",
                    models.CharField(
                        choices=[("PC", "PC"), ("모바일", "모바일")],
                        max_length=10,
                        verbose_name="고객 가입경로",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객",
                "verbose_name_plural": "고객",
            },
        ),
    ]
