# Generated by Django 5.1.2 on 2024-12-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_consumer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="consumer_last_connection_dt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="고객 최종접속일"
            ),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="consumer_last_order_dt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="고객 최종주문일"
            ),
        ),
    ]
