# Generated by Django 5.1.2 on 2024-12-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_alter_consumer_consumer_last_connection_dt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_seo_author",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_seo_description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_seo_keywords",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_seo_title",
        ),
    ]
