# Generated by Django 5.1.2 on 2024-12-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_category_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_option',
            field=models.CharField(blank=True, max_length=1000, verbose_name='상품 옵션'),
        ),
    ]
