# Generated by Django 5.1.2 on 2024-12-04 04:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_product_product_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(), blank=True, size=None, verbose_name='상품 상세페이지'),
        ),
    ]
