# Generated by Django 5.1.2 on 2024-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_product_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_keywords',
            field=models.CharField(max_length=1000, verbose_name='상품 검색어'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_seo_keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='검색용 검색어'),
        ),
    ]
