# Generated by Django 5.1.2 on 2024-12-04 23:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_product_product_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, size=None, verbose_name='상품 상세페이지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail_image',
            field=models.ImageField(upload_to='product_thumbnail_images/', verbose_name='상품 이미지'),
        ),
    ]
