# Generated by Django 5.1.2 on 2024-12-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_product_product_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_consumer_price',
            field=models.PositiveIntegerField(default=0, verbose_name='상품 소비자가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='상품 요약설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='상품 검색어'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sell_price',
            field=models.PositiveIntegerField(default=0, verbose_name='상품 판매가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_supply_price',
            field=models.PositiveIntegerField(default=0, verbose_name='상품 공급가'),
        ),
    ]
