# Generated by Django 5.1.2 on 2024-12-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_product_product_consumer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='consumer_verified',
        ),
        migrations.AddField(
            model_name='consumer',
            name='consumer_verify_dt',
            field=models.DateField(blank=True, null=True, verbose_name='고객 인증일자'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='consumer_verify_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='고객 인증정보'),
        ),
    ]
