# Generated by Django 5.1.2 on 2024-12-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_consumer_consumer_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_smartstore_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='스마트스토어 상품코드'),
        ),
        migrations.AddField(
            model_name='productoptions',
            name='product_option_smartstore_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='상품 옵션 스마트스토어 코드'),
        ),
    ]
