# Generated by Django 5.1.2 on 2024-12-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_product_product_smartstore_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_smartstore_channel_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='스마트스토어 상품코드'),
        ),
    ]
