# Generated by Django 5.1.2 on 2024-12-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_product_product_smartstore_channel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptions',
            name='product_option_code',
        ),
        migrations.AddField(
            model_name='productoptions',
            name='product_option_cafe24_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='상품 옵션 카페24 코드'),
        ),
    ]
