# Generated by Django 5.1.2 on 2024-12-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_productoptions_product_option_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptions',
            name='product_option_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='상품 옵션 코드'),
        ),
    ]
