# Generated by Django 5.1.2 on 2024-12-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_productoptions_product_option_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_smartstore_keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='스마트스토어 검색어'),
        ),
    ]
