# Generated by Django 5.1.2 on 2024-12-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_product_product_smartstore_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_coupang_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='쿠팡 상품코드'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_coupang_keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='쿠팡 검색어'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_smartstore_channel_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='스마트스토어 상품채널코드'),
        ),
    ]
