# Generated by Django 5.1.2 on 2024-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_product_product_coupang_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_coupang_is_prohibitted',
            field=models.BooleanField(default=False, verbose_name='쿠팡 제한 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_smartstore_is_prohibitted',
            field=models.BooleanField(default=False, verbose_name='스마트스토어 제한 여부'),
        ),
    ]
