# Generated by Django 5.1.2 on 2024-12-11 00:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_product_product_coupang_is_prohibitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_origin_detail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, default=list, size=None, verbose_name='상품 원본 상세페이지'),
        ),
    ]
