# Generated by Django 5.1.2 on 2024-12-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_product_product_origin_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_esm_plus_auction_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='ESM+ 옥션 상품코드'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_esm_plus_auction_is_prohibitted',
            field=models.BooleanField(default=False, verbose_name='ESM+ 옥션 제한 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_esm_plus_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='ESM+ 상품코드'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_esm_plus_gmarket_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='ESM+ 지마켓 상품코드'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_esm_plus_gmarket_is_prohibitted',
            field=models.BooleanField(default=False, verbose_name='ESM+ 지마켓 제한 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_esm_plus_is_prohibitted',
            field=models.BooleanField(default=False, verbose_name='ESM+ 제한 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_origin_thumbnail_image',
            field=models.CharField(blank=True, max_length=1000, verbose_name='상품 원본 이미지'),
        ),
    ]
