# Generated by Django 5.1.2 on 2024-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_product_product_esm_plus_auction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cafe24_is_prohibitted',
            field=models.BooleanField(default=False, verbose_name='카페24 제한 여부'),
        ),
    ]
