# Generated by Django 5.1.2 on 2024-12-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_product_product_cafe24_is_prohibitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_manager_price',
            field=models.PositiveIntegerField(default=0, verbose_name='상품 관리자가'),
        ),
    ]
