# Generated by Django 5.1.2 on 2024-12-13 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_product_product_manager_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_new',
            field=models.BooleanField(default=False, verbose_name='상품 신상품 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_is_recommend',
            field=models.BooleanField(default=False, verbose_name='상품 추천 여부'),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='product_option_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='상품 옵션 코드'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='상품')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productoptions', verbose_name='상품 옵션')),
            ],
            options={
                'verbose_name': '장바구니 아이템',
                'verbose_name_plural': '장바구니 아이템',
                'unique_together': {('member', 'product', 'product_option')},
            },
        ),
    ]
