# Generated by Django 5.1.2 on 2024-12-17 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_cartitem_product_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='consumer_channel',
            field=models.CharField(choices=[('스마트스토어', '스마트스토어'), ('카페24', '카페24'), ('쿠팡', '쿠팡'), ('ESM+', 'ESM+'), ('ESM+ 지마켓', 'ESM+ 지마켓'), ('ESM+ 옥션', 'ESM+ 옥션'), ('수동주문', '수동주문')], default='카페24', max_length=30, verbose_name='고객 채널'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumer_register_path',
            field=models.CharField(choices=[('PC', 'PC'), ('모바일', '모바일')], default='모바일', max_length=10, verbose_name='고객 가입경로'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_channel', models.CharField(choices=[('스마트스토어', '스마트스토어'), ('카페24', '카페24'), ('쿠팡', '쿠팡'), ('ESM+', 'ESM+'), ('ESM+ 지마켓', 'ESM+ 지마켓'), ('ESM+ 옥션', 'ESM+ 옥션'), ('수동주문', '수동주문')], default='수동주문', max_length=30, verbose_name='주문 채널')),
                ('order_code', models.CharField(max_length=30, unique=True, verbose_name='주문 관리용 코드')),
                ('order_number', models.CharField(blank=True, max_length=30, verbose_name='주문번호')),
                ('order_product_order_number', models.CharField(blank=True, max_length=30, verbose_name='상품주문번호')),
                ('order_quantity', models.PositiveIntegerField(default=1, verbose_name='주문 수량')),
                ('order_price', models.IntegerField(default=0, verbose_name='주문 가격')),
                ('order_delivery_method', models.CharField(choices=[('롯데택배', '롯데택배'), ('GS 반값택배', 'GS 반값택배'), ('CU 반값택배', 'CU 반값택배'), ('스토어픽업', '스토어픽업')], default='롯데택배', max_length=30, verbose_name='주문 배송방법')),
                ('order_tracking_number', models.CharField(blank=True, max_length=30, verbose_name='주문 운송장번호')),
                ('order_delivery_fee', models.PositiveIntegerField(default=0, verbose_name='주문 배송비')),
                ('order_status', models.CharField(choices=[('입금대기', '입금대기'), ('상품발주대기', '상품발주대기'), ('상품발주완료', '상품발주완료'), ('상품검수중', '상품검수중'), ('상품검수완료', '상품검수완료'), ('상품포장중', '상품포장중'), ('상품포장완료', '상품포장완료'), ('발송대기', '발송대기'), ('발송완료', '발송완료'), ('배송중', '배송중'), ('배송완료', '배송완료'), ('취소요청', '취소요청'), ('취소완료', '취소완료'), ('환불요청', '환불요청'), ('환불완료', '환불완료'), ('교환요청', '교환요청'), ('교환완료', '교환완료')], default='입금대기', max_length=30, verbose_name='주문 상태')),
                ('order_deposit_bank_info', models.CharField(blank=True, max_length=200, verbose_name='주문 입금은행 정보')),
                ('order_deposit_name', models.CharField(blank=True, max_length=30, verbose_name='주문 입금자명')),
                ('order_payment_method', models.CharField(blank=True, max_length=30, verbose_name='주문 결제방법')),
                ('order_payment_amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='주문 결제금액')),
                ('order_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='주문 생성일시')),
                ('order_modified_datetime', models.DateTimeField(auto_now=True, verbose_name='주문 수정일시')),
                ('order_payment_completed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='주문 결제완료일시')),
                ('order_delivery_expected_datetime', models.DateTimeField(blank=True, null=True, verbose_name='주문 예상배송일시')),
                ('order_delivery_started_datetime', models.DateTimeField(blank=True, null=True, verbose_name='주문 배송시작일시')),
                ('order_delivery_completed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='주문 배송완료일시')),
                ('order_receiver_name', models.CharField(blank=True, max_length=30, verbose_name='주문 수취인명')),
                ('order_receiver_phone_number', models.CharField(blank=True, max_length=30, verbose_name='주문 수취인 전화번호')),
                ('order_receiver_address', models.CharField(blank=True, max_length=200, verbose_name='주문 수취인 주소')),
                ('order_receiver_detail_address', models.CharField(blank=True, max_length=100, verbose_name='주문 수취인 상세주소')),
                ('order_receiver_message', models.CharField(blank=True, max_length=200, verbose_name='주문 수취인 배송메시지')),
                ('order_consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.consumer', verbose_name='주문 고객')),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product', verbose_name='주문 상품')),
                ('order_product_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productoptions', verbose_name='주문 상품 옵션')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
            },
        ),
        migrations.CreateModel(
            name='Settle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle_amount', models.IntegerField(default=0, verbose_name='정산 금액')),
                ('settle_status', models.CharField(choices=[('정산대기', '정산대기'), ('정산완료', '정산완료'), ('정산취소', '정산취소')], default='정산대기', max_length=30, verbose_name='정산 상태')),
                ('settle_datetime', models.DateTimeField(blank=True, null=True, verbose_name='정산 일시')),
                ('settle_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='정산 생성일시')),
                ('settle_modified_datetime', models.DateTimeField(auto_now=True, verbose_name='정산 수정일시')),
                ('settle_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.order', verbose_name='정산 주문')),
            ],
            options={
                'verbose_name': '정산',
                'verbose_name_plural': '정산',
            },
        ),
    ]
