# Generated by Django 5.1.2 on 2024-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_new',
            field=models.BooleanField(default=False, verbose_name='상품 신상품 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_is_recommend',
            field=models.BooleanField(default=False, verbose_name='상품 추천 여부'),
        ),
    ]
