# Generated by Django 5.1.2 on 2024-12-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_order_settle_consumer_consumer_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_smartstore_channel_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_smartstore_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_smartstore_is_prohibitted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_smartstore_keywords',
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumer_base_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='고객 기본주소'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumer_birth',
            field=models.DateField(blank=True, null=True, verbose_name='고객 생년월일'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumer_channel',
            field=models.CharField(choices=[('카페24', '카페24'), ('쿠팡', '쿠팡'), ('ESM+', 'ESM+'), ('ESM+ 지마켓', 'ESM+ 지마켓'), ('ESM+ 옥션', 'ESM+ 옥션'), ('수동주문', '수동주문')], default='카페24', max_length=30, verbose_name='고객 채널'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_channel',
            field=models.CharField(choices=[('카페24', '카페24'), ('쿠팡', '쿠팡'), ('ESM+', 'ESM+'), ('ESM+ 지마켓', 'ESM+ 지마켓'), ('ESM+ 옥션', 'ESM+ 옥션'), ('수동주문', '수동주문')], default='수동주문', max_length=30, verbose_name='주문 채널'),
        ),
    ]
