# Generated by Django 5.1.2 on 2024-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_consumer_consumer_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settle',
            name='settle_datetime',
        ),
        migrations.AddField(
            model_name='settle',
            name='settle_completed_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='정산 완료일시'),
        ),
        migrations.AddField(
            model_name='settle',
            name='settle_expected_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='정산 예상일시'),
        ),
    ]
