# Generated by Django 5.1.2 on 2024-12-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_product_product_is_new_product_product_is_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptions',
            name='product_option_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='상품 옵션 코드'),
        ),
    ]
