# Generated by Django 5.1.2 on 2024-12-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_remove_product_product_smartstore_channel_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptions',
            name='product_option_smartstore_code',
        ),
    ]
