# Generated by Django 5.1.2 on 2024-12-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_remove_settle_settle_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='consumer_id',
            field=models.CharField(max_length=30, verbose_name='고객 아이디'),
        ),
    ]
