# Generated by Django 5.1.2 on 2024-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_remove_productoptions_product_option_smartstore_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_origin_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='상품 원본 URL'),
        ),
    ]
