# Generated by Django 5.1.2 on 2025-01-07 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_product_product_origin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_thumbnail_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='상품 이미지 파일 이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None, verbose_name='상품 상세페이지'),
        ),
    ]
